### ISSUE TITLE
Assertion failed on startup proxy_pixbuf != NULL

### ISSUE THREAD

**Issue by timonv** [birdieapp/birdie#110]
The error:

```
TypeError: Must be number, not NoneType
**
Gtk:ERROR:gtkicontheme.c:3956:proxy_pixbuf_destroy: assertion failed: (icon_info->proxy_pixbuf != NULL)
```

I'm running Archlinux, everything up to date. Starting up X with startx, which launches I3.

Let me know if I can help out with more package info, etcetera. Seems there are other people with the issue as well.

https://aur.archlinux.org/packages/birdie-git/

**Comment by nathandyer** [comment]
Hi! I believe this issue is fixed in Birdie 2.0. Also, just in case you haven't heard the news yet, we have decided to focus on elementary OS, which means we are dropping official support for Arch and all other Linux platforms. Please read our [announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) for more information. Thank you so much for the report!
