### ISSUE TITLE
installing from yum repo on Fedora 22 breaks terminal

### ISSUE THREAD

**Issue by dmison** [birdieapp/birdie#123]
I added the fedora 20 yum repo to fedora 22 & the app installs and works perfectly when I installed it via `dnf install birdie`.

However the repo also contains a `gnome-terminal-darth-edition` package.  The next time I did a `dnf update` the F22 gnome-terminal package was replaced by this older package.This created an issue on Fedora22 as described here https://bugzilla.redhat.com/show_bug.cgi?id=1234212

Assuming that the package was required for F20, suggest also supplying a F22 repo that does not have that package.

**Comment by nathandyer** [comment]
Hi! I'm sorry, I don't know anything about the yum repo, or why in the world it would contain a "Darth Edition" of GNOME Terminal. That said, we recently announced that we are focusing on elementary OS, and are therefore dropping support for all other Linux platforms. Because of this, I'm going to close the issue. Please take a look at our [announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) for more information. Thank you for your report!
