### ISSUE TITLE
Birdie 1.1.0  with Xubuntu Trusty 14.04.3  = 100% CPU

### ISSUE THREAD

**Issue by jdt37b** [birdieapp/birdie#132]
Hello, 
Birdie 0.3.7, version of Precise 12.04, is Ok.
Whith Trusty 14.04, the starting of Birdie is also ok, but when my mouse flies over the window of Birdie (to scroll for ex.)  the CPU is 100% and it's necessary to cancel Birdie.
The 1.1.0  version is unusable.
For information, starting Birdie in line command : no message.
What's the problem ?  (OpenGL ?)
Thanks.

**Comment by theonlydoo** [comment]
Try using birdie 2, the proble doesn't occur

**Comment by jdt37b** [comment]
Birdie 2 is not avalable with Ubuntu 14.04, 32 and 64 bits, on http://www.birdieapp.eu/
I am waiting !

**Comment by theonlydoo** [comment]
It's not available anywhere, you have to compile from the github repo

**Comment by jdt37b** [comment]
Thank you, I tried compiling without success.
In "birdieapp.eu" the link "Here" to the "tarball" is KO and then I got errors messages with cmake.
Too complicated for me, I only know that using PPA's !
Good day.

**Comment by nathandyer** [comment]
Hi! This issue is indeed fixed now. However, please note that we recently announced that we are focusing on elementary OS, and are therefore dropping support for all other Linux platforms. You are welcome to try and use Birdie, but to be completely honest with you, you will almost certainly get a better experience in Ubuntu with another app, such as Corebird. [Please read our announcement to find out more.](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) Thank you!

**Comment by jdt37b** [comment]
Hello and thank you for your answer.
Alas, for Corebird (ppa : ppa:ubuntuhandbook1/corebird) and Ubuntu 14.04 there are dependences problems (libgtk-3-0 >=3.11.2 is no present).
Nice day.
