### ISSUE TITLE
birdie not found message when 'add a existing account'

### ISSUE THREAD

**Issue by moein5** [birdieapp/birdie#142]
hi
i just installed birdie on ubuntu 15.10, when i try to add my account a blank page will open and says not found 404. it's same as create new account button

**Comment by nathandyer** [comment]
Hi! This should be fixed in the 2.0 release. Please note, however, that we recently announced that we are focusing on elementary OS and are dropping support for all other Linux platforms. Please check out the [announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) for more details. Thank you!
