### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by jonscyriac** [birdieapp/birdie#143]
when i do cmake i get this error
no cmakelists.txt

i just skipped over it by making a plain txt file with the same name

i again get an error when i do make install saying no rule to target 'install'

Im new to building/compiling. Please help

**Comment by nathandyer** [comment]
Hi @jonscyriac!

First, you'll need to install all of the necessary development packages (which you can find a list of in the INSTALL file). Then, just perform these steps in the terminal:

git clone https://github.com/birdieapp/birdie.git
cd birdie
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
sudo make install 

Please note that we recently switched to only officially supporting elementary OS, so you may have a difficult time compiling Birdie on another platform. I hope that helps a bit! I'm going to go ahead and close this issue since it's not a problem with the app, but if you still have a difficult time understanding how to compile, I recommend asking around online to learn more. For example, the [elementary OS Stack Exchange](http://elementaryos.stackexchange.com/) is really excellent and they are friendly with newcomers.

All my best,
- Nathan
