### ISSUE TITLE
Add support for Tweet Marker Edit

### ISSUE THREAD

**Issue by vascomfnunes** [birdieapp/birdie#6]
Reported by Sebastián Porta on 2013-03-26

Would be great if you add Tweet Marker support for syncing timeline positions between devices.

http://tweetmarker.net/

**Comment by neerolyte** [comment]
This seems to be closed by mistake. Could it at least be reopened?

**Comment by nathandyer** [comment]
In the research I've done, Tweet Marker doesn't appear to by used by any of the major Twitter apps (including the official client) on Android, iOS, Mac, or Windows. I'm going to mark this as a "Won't Fix" because the amount of effort it would take to implement this just doesn't seem worth it given the relatively tiny payoff.

**Comment by mcg** [comment]
Tweetbot, Fenix, Talon, Flamingo and more support TweetMarker. The official client is never likely to support a 3rd party service like this. Hopefully you'd reconsider supporting.
